apiVersion: apps/v1
kind: Deployment
metadata:
  name: emb
  namespace: finance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emb
  template:
    metadata:
      labels:
        app: emb
    spec:
      nodeSelector:
        node-type: gpu
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      containers:
        - name: emb
          image: nvcr.io/nim/nv-embedqa-e5-v5:latest
          imagePullPolicy: Always
          resources:
            limits:
              nvidia.com/gpu: 1
          ports:
            - containerPort: 8000
      imagePullSecrets:
        - name: ngc-secret
---
apiVersion: v1
kind: Service
metadata:
  name: emb
  namespace: finance
spec:
  selector:
    app: emb
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
