apiVersion: batch/v1
kind: Job
metadata:
  name: ingest-job
  namespace: finance
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: ingest
        image: 825478277022.dkr.ecr.us-east-1.amazonaws.com/finx-ingest:latest
        env:
        - name: DB_URL
          value: "postgresql://postgres:postgres@pg.finance.svc.cluster.local:5432/postgres"