apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm
  namespace: finance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm
  template:
    metadata:
      labels:
        app: llm
    spec:
      nodeSelector:
        node-type: gpu
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      containers:
        - name: llm
          image: nvcr.io/nim/llama-3.1-nemotron-nano-8b-v1:latest
          imagePullPolicy: Always
          resources:
            limits:
              nvidia.com/gpu: 1
          ports:
            - containerPort: 8000
      imagePullSecrets:
        - name: ngc-secret
---
apiVersion: v1
kind: Service
metadata:
  name: llm
  namespace: finance
spec:
  selector:
    app: llm
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
