version: "3.9"
services:
  pg:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  orchestrator:
    build:
      context: ../orchestrator
      dockerfile: Dockerfile
    environment:
      SIM_MODE: "true"
      DB_URL: "postgresql://postgres:postgres@pg:5432/postgres"
    depends_on:
      pg:
        condition: service_healthy
    ports:
      - "5000:5000"

volumes:
  pg_data: