version: "3.9"
services:
  pg:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  orchestrator:
    build:
      context: ..
      dockerfile: orchestrator/Dockerfile
    environment:
      SIM_MODE: ${SIM_MODE}
      DB_URL: ${DB_URL}
      NIM_LLM_URL: ${NIM_LLM_URL}
      NIM_EMB_URL: ${NIM_EMB_URL}
      REQUEST_TIMEOUT: ${REQUEST_TIMEOUT}
      TOP_K: ${TOP_K}
    depends_on:
      - pg
    ports:
      - "5000:5000"

  # GPU services (placeholders - only run when you have GPU runtime available)
  llm:
    image: nvcr.io/nim/llama-3.1-nemotron-nano-8b-v1:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: ["gpu"]
    ports:
      - "8002:8000"

  emb:
    image: nvcr.io/nim/nv-embedqa-e5-v5:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: ["gpu"]
    ports:
      - "8001:8000"

volumes:
  pgdata:
