apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-data
  labels:
    app: pg
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg
  template:
    metadata:
      labels:
        app: pg
    spec:
      nodeSelector:
        node-type: cpu
      containers:
        - name: pg
          image: postgres:16
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: finx
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pg-data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
      volumes:
        - name: pg-data
          persistentVolumeClaim:
            claimName: pg-data

---
apiVersion: v1
kind: Service
metadata:
  name: pg
spec:
  type: ClusterIP
  selector:
    app: pg
  ports:
    - port: 5432
      targetPort: 5432

## we dont have the AWS EBS CSI driver so gp2 PVCs bind wont have persistent storage. remember that