apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg
  template:
    metadata:
      labels:
        app: pg
    spec:
      # If your node is already labeled node-type=cpu, keep this.
      # If not labeled, either label the node or remove this block.
      nodeSelector:
        node-type: cpu

      containers:
        - name: pg
          image: pgvector/pgvector:pg16   # this is the important change
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: finx
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pg-data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"

      volumes:
        - name: pg-data
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: pg
spec:
  selector:
    app: pg
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
